version: "3.9"
services:
    web:
        image: tovanijonatas/php839-jsadvogados:v1.2
        container_name: web
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            args:
                PHP_VERSION: '8.3.9-fpm-bullseye'
