version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default-certbot.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/certbot/www:/var/www/certbot
    networks:
      - certbot_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  certbot_net:
    driver: overlay
    attachable: true
