version: "3.9"

services:
    # Serviço PHP
    web:
        image: tovanijonatas/php839-jsadvogados:v1
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "1"
                    memory: 1G
                reservations:
                    cpus: "0.1"
                    memory: 20M
            restart_policy:
                condition: on-failure

        networks:
            - laravel
        environment:
            - PHP_VERSION=8.3.9-fpm-bullseye

    # Serviço Nginx
    nginx:
        image: nginx:alpine
        deploy:
            replicas: 2
            placement:
                constraints: [node.role == manager] # Opcional: rodar apenas nos nodes managers
        ports:
            - "80:80" # Porta para HTTP
            - "443:443" # Porta para HTTPS
        volumes:
            - ./docker/nginx/sites.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/error.html:/var/www/html/error.html
            - ./app:/var/www/app
        networks:
            - laravel

    # Serviço Redis
    phpredis:
        image: redis:alpine
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        networks:
            - laravel
        volumes:
            - ./.docker/redis:/data
        # Remove as portas para manter acesso apenas pela rede interna

    # Serviço PostgreSQL
    postgres:
        image: postgres:16.3
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        environment:
            POSTGRES_DB: app-js-dev
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        networks:
            - laravel
        volumes:
            - postgres_data:/var/lib/postgresql/data
        # Remove as portas para manter acesso apenas pela rede interna

    # Serviço PgAdmin
    pgadmin:
        image: dpage/pgadmin4
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        environment:
            PGADMIN_DEFAULT_EMAIL: "dev@example.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        networks:
            - laravel
        volumes:
            - ./app/data/pgadmin:/var/lib/pgadmin
        # Remove as portas para manter acesso apenas pela rede interna

networks:
    laravel:
        driver: overlay
        attachable: true

volumes:
    postgres_data:
