version: "3.7"

services:

    # redis
    phpredis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - './.docker/redis:/data'
        container_name: phpredis
        restart: unless-stopped
        networks:
            - laravel

    postgres:
        image: postgres:16.3
        container_name: postgres
        environment:
            POSTGRES_DB: app-js-dev
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel
        restart: unless-stopped

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: "dev@example.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "15432:80"
        volumes:
            - ./data/pgadmin:/var/lib/pgadmin
        networks:
            - laravel

    pgbackup:
        image: postgres:16.3
        networks:
        - laravel
        command: sleep infinity  # fica parado, aguardando seu comando

networks:
    laravel:
        driver: bridge

volumes:
    postgres_data:
