@extends('layouts.pdf.master')

@section('title', 'Invoice PDF')

@section('header')
    <h1>Company Name</h1>
@endsection

@section('content')
    {{-- <pre>{{ print_r($dataEnv, true) }}</pre> --}}
    {{-- <pre>{{ print_r($dataEnv, true) }}</pre> --}}
    <div class="table-responsive mt-2">
        <table class="table-striped table" style="border-collapse: collapse;">
            <thead>
                <tr>
                    <th class="text-nowrap">Status</th>
                    <th class="text-nowrap" title="Tipo de movimentação">Tipo Mov.</th>
                    <th class="text-nowrap" title="Valor Movimentado">Valor Mov.</th>
                    <th class="text-nowrap" title="Data Movimentação">Data Mov.</th>
                    <th class="text-nowrap">Descrição</th>
                    <th class="text-nowrap">Dados Específicos</th>
                    <th class="text-nowrap" title="Participante(s) do valor a receber">Participante(s)</th>
                    <th class="text-nowrap" title="Integrante(s) de grupo(s)">Integrante(s)</th>
                    <th class="text-nowrap">Cadastro</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($dataEnv['dados'] as $dado)
                    <tr>
                        <td>{{ $dado['status'] ?? '' }}</td>
                        <td>{{ $dado['movimentacao_tipo'] ?? '' }}</td>
                        <td>{{ $dado['valor_movimentado'] ?? '' }}</td>
                        <td>{{ $dado['data_movimentacao'] ?? '' }}</td>
                        <td>{{ $dado['descricao_automatica'] ?? '' }}</td>
                        <td>{{ $dado['dados_especificos'] ?? '' }}</td>
                        <td>{{ $dado['participantes'] ?? '' }}</td>
                        <td>{{ $dado['integrantes'] ?? '' }}</td>
                        <td>{{ $dado['created_at'] ?? '' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

@endsection

@section('footer')
    <p>Generated by MyApp - {{ date('Y-m-d') }}</p>
@endsection
