@extends('layouts.pdf.master')

@section('title', 'Invoice PDF')

@section('header')
    <h1>Company Name</h1>
@endsection

@section('content')
    <h2>Invoice #{{ $invoice->id }}</h2>
    <p>Date: {{ $invoice->date }}</p>
    <p>Amount: {{ $invoice->amount }}</p>
@endsection

@section('footer')
    <p>Generated by MyApp - {{ date('Y-m-d') }}</p>
@endsection
